spring:
 # Object Mapper
 jackson:
   property-naming-strategy: SNAKE_CASE
   serialization:
     write-dates-as-timestamps: false
   default-property-inclusion: non_null
   deserialization:
     read-unknown-enum-values-using-default-value: true
   mapper:
     accept-case-insensitive-enums: true
 # DataSource
 datasource:
  url: jdbc:mysql://yhrz9vns005e0734.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/uf407xfptfb5yyjg?serverTimezone=GMT-3
  username: uoasee87o2ae8h9l
  password: bl0vf885e6l79v8v
  driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
   initial-size: 6
   max-active: 6
   max-idle: 5
   min-idle: 2
# JPA
  jpa:
   show-sql: true
   generate-ddl: false #primera ejecucion debe estar en true, el resto false
   properties-hibernate:
    format_sql: true
    dialect: org.hibernate.dialect.MySQL8Dialect
   hibernate:
    use-new-id-generator-mappings: false
# Ajustes de nivel de logging
spring.http.log-request-details: false
logging:
 level:
  root: INFO
  org.springframework.web: INFO
  org.springframework.web.HttpLogging: INFO
  org.springframework.security: DEBUG
# Swagger
swagger:
  host:
    url: https://bank-api-integrations.herokuapp.com

# CORS
cors-config:
  allowed-origins:
    - https://bank-app-int.herokuapp.com
    - http://localhost:8080
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PATCH
  allowed-headers:
    - Content-Type