logging:
 level:
  root: INFO
  org.springframework.web: INFO
 # DataSource
spring:
 datasource:
  url: jdbc:mysql://yhrz9vns005e0734.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/uf407xfptfb5yyjg?serverTimezone=GMT-3
  username: uoasee87o2ae8h9l
  password: bl0vf885e6l79v8v
  driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
   initial-size: 6
   max-active: 6
   max-idle: 5
   min-idle: 2
 # JPA
 jpa:
  show-sql: true
  generate-ddl: false #primera ejecucion debe estar en true, el resto false
  properties-hibernate:
   format_sql: true
   dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate:
   use-new-id-generator-mappings: false